### ISSUE TITLE
2.13.1 removes working configuration

### ISSUE THREAD

**Issue by embcla** [mKeRix/room-assistant#542] opened 2021-02-14 15:47 UTC
**Describe the bug**
Due to breaking changes in the supervisor, room-assistant 2.13.1 changes its configuration to a new blank one and that's OK. 
But it does so forgetting everything from the previous configuration. 

**To reproduce**
Configure an instance of any version prior to 2.13.1 and then update, the new one will have a blank configuration. 

**Relevant logs**

**Relevant configuration**
Any

**Expected behavior**
Automatic copy of the previous configuration or at least a warning in the logs and a backup copy of the previous configuration

**Environment**
 - room-assistant version: [2.13.1]
 - installation type: [Hass.io]
 - hardware: [AMD x86 + debian]
 - OS: [debían 10]

**Additional context**

**Comment by mKeRix** [comment] 2021-02-22 20:27
I know this is annoying, but unfortunately there was no easy way of even getting the old config after the sudden breaking change in the HA supervisor. Any time the add-on is restarted it would have applied the new supervisor behavior, which includes any upgrades. Best that I could've done would have been restoring some parts of your config, but then you'd suddenly have half right, half wrong configs saved into your folder. It would have also been a lot of work... so in the interest of getting this to work again I opted to just go the quick route.

I'll close this issue as intended behavior, but I'm happy to continue discussing if you want. I'm sorry that this whole things has been kind of awkward, but I was really at the mercy of the supervisor project here (see also #501).

**Closed by mKeRix** 2021-02-22 20:27 UTC
Labels: bug
