### ISSUE TITLE
Raspberry Pi only showing one bluetooth adapter when using a USB bluetooth dongle

### ISSUE THREAD

**Issue by julianrinaldi** [mKeRix/room-assistant#331] opened 2020-11-02 01:32 UTC
Whenever I plug a USB dongle into a Raspberry Pi, that dongle becomes hci0 and the internal bluetooth adapter for the Raspberry Pi no longer shows up. Is this normal behavior? I wanted a USB dongle to use for tracking BLE trackers and then use the internal one for Bluetooth Classic

This is the case when plugging it into a Raspberry Pi 3+, 4 B and zero. Am I doing something wrong?

**Comment by mKeRix** [comment] 2020-11-02 08:19
This is an issue with the current versions of Raspbian, see #300 for more info and tips on how to fix it. In the latest version of room-assistant you can now also run both BLE and BT Classic off the same adapter, so that may be an alternative you could consider.

I'll close this issue since the cause isn't within room-assistant, but please do not hesitate to comment again should you have more questions.

**Closed by mKeRix** 2020-11-02 08:19 UTC
Labels: bug
