### ISSUE TITLE
preserve last status after switching off Bluetooth Inquiries

### ISSUE THREAD

**Issue by MarpleA** [mKeRix/room-assistant#264] opened 2020-08-13 13:02 UTC
Hi,

I don't know if this is by design or a bug. I use Home Assistant connected to my single room assistant device (raspberry pi zero w).

At my home, room assistant bluetooth connection causes heaps of trouble for my Wifi network and therefore I thought about triggering room assistant only when the front door has been opened and switch it off again 5 minutes later. During this period of time room assistant can detect if people are at home or not respectively arrived or left home.
So far so good but If the bluetooth inquiries switch has been switched off again device states change to not_home.
This way presence detection doesn't make sense.

Isn't it possible to preserve the last state of room presence after switching of the bluetooth inquiries switch?
if not, what's the purpose of the inquiries switch? I can't think of a scenario where it would make sense then.

Best

**Comment by mKeRix** [comment] 2020-08-14 09:35
Currently it's by design, although I plan to add a setting that would allow you to choose the behavior that you need. Since this is a duplicate of #156 let's track it there!

**Closed by mKeRix** 2020-08-14 09:35 UTC
