### ISSUE TITLE
Hass.io Watchdog keeps restarting the add-on

### ISSUE THREAD

**Issue by Veldkornet** [mKeRix/room-assistant#322] opened 2020-10-28 14:21 UTC
**Describe the bug**
My Raspberry Pi 4 running Hassio recently updated the supervisor to 2020.10.0 and room-assistant to 2.11.2, and it seems (only with room-assistant) that the watchdog keeps restarting the addon for no apparent reason. I don't recall seeing this behavior prior to 2.11.2 (or supervisor 2020.10.0)

If I turn watchdog off, the add-on continues to run without problem

**To reproduce**
Enable watchdog on the add-on 

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
20-10-28 13:00:43 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:02:43 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:02:43 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:02:44 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:02:45 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:04:45 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:06:45 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:06:45 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:06:46 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:06:47 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:08:47 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:10:47 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:10:47 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:10:48 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:10:49 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:12:49 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:14:49 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:14:49 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:14:49 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:14:50 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:16:50 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:18:50 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:18:50 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:18:51 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:18:52 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:20:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:22:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:22:52 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:22:53 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:22:54 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:24:54 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:26:54 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:26:54 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:26:55 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:26:56 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:28:56 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:30:56 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:30:56 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:30:57 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:30:57 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:32:57 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:34:57 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:34:57 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:34:58 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:34:59 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:36:59 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:38:59 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:38:59 INFO (SyncWorker_7) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:39:00 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:39:01 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
20-10-28 13:41:01 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
20-10-28 13:43:01 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
20-10-28 13:43:01 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
20-10-28 13:43:03 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
20-10-28 13:43:04 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.11.2
```

**Expected behavior**
Watchdog should only restart the add-on if it crashes

**Environment**
 - room-assistant version: 2.11.2
 - installation type: Hass.io (64-bit)
 - hardware: RaspberryPi 4 - 4GB
 - OS: HomeAssistantOS

**Comment by mKeRix** [comment] 2020-10-28 15:59
The restart is caused by the health check, and I'm pretty sure that I introduced a small bug for the health check when I implemented the lock thing that was included in the last version. If that exception happens a few times in succession for some reason it will mark the instance as unhealthy.

Should be a fairly easy fix hopefully, I'll try to work on this later today. Thanks for reporting!

**Comment by embcla** [comment] 2020-10-28 18:32
I didn't bother putting in a ticket, just disabled the watchdog
but this has been in since at least 2.10

**Comment by mKeRix** [comment] 2020-10-28 20:28
Turns out my assumption from above was not the case, I just remembered it wrong. In that case I will disable the specific watchdog feature that causes this in the next add-on version, so that it can be used for restarting the add-on again.

**Comment by mKeRix** [comment] 2020-10-31 22:18
Should be fixed in 2.11.3, I've disabled the feature that was causing this. I couldn't reproduce it on my Home Assistant Supervised setup, but it's a NUC without Bluetooth so the environment isn't really the same. I can take another look at adding the feature back once I've tested it some more on Pi with Home Assistant OS.

**Closed by mKeRix** 2020-10-31 22:18 UTC
Labels: bug

**Comment by johntdyer** [comment] 2023-05-16 16:44
I seem to be getting this again

Home Assistant 2023.5.3 
Supervisor 2023.04.1 
Operating System 10.1
 Frontend 20230503.3 - latest 


```
23-05-16 12:25:50 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
23-05-16 12:25:50 INFO (SyncWorker_9) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
23-05-16 12:25:51 INFO (SyncWorker_9) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
23-05-16 12:25:51 INFO (SyncWorker_11) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-amd64 with version 2.20.0
23-05-16 12:27:51 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
23-05-16 12:29:51 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
23-05-16 12:29:51 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
23-05-16 12:29:52 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
23-05-16 12:29:52 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-amd64 with version 2.20.0
23-05-16 12:31:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
23-05-16 12:33:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
23-05-16 12:33:52 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
23-05-16 12:33:52 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
23-05-16 12:33:52 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-amd64 with version 2.20.0
23-05-16 12:35:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 6e66619d_room_assistant
23-05-16 12:37:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 6e66619d_room_assistant application!
23-05-16 12:37:52 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
23-05-16 12:37:53 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
23-05-16 12:37:53 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-amd64 with version 2.20.0

```

 Should I open a new ticket?

**Comment by johntdyer** [comment] 2023-05-16 17:30
actually nevermind, it was 100% a config issue on my end... :)

**Comment by JAudi23** [comment] 2023-08-17 14:12
What was the config issue?  your issue resolution may help others.
