### ISSUE TITLE
missing dependency libudev-dev for raspbian

### ISSUE THREAD

**Issue by hillbicks** [mKeRix/room-assistant#134] opened 2020-03-09 20:40 UTC
I just wanted to let you know that the default installation of raspbian is missing the libudev-dev which is a requirement for building room-assistant. 

Can you add that to this command?

`sudo apt-get install libavahi-compat-libdnssd-dev`

**Comment by mKeRix** [comment] 2020-03-10 20:19
The dependency that requires libudev-dev is marked as optional, as room-assistant can be run without it. It's documented on the [BLE integration page](https://www.room-assistant.io/integrations/bluetooth-low-energy.html#requirements), as that's the integration that actually needs it. The documentation is split by design for the flexibility.

**Closed by mKeRix** 2020-03-10 20:19 UTC

**Comment by s1rd4v3** [comment] 2021-01-10 22:16
@hillbicks thanks a lot. was searching quite some time to get rid of the error while installing globally the room-assistant package!
