### ISSUE TITLE
Display RSSI and advertised measured power in /entities API 

### ISSUE THREAD

**Issue by marrold** [mKeRix/room-assistant#203] opened 2020-05-28 02:06 UTC
First of all, thanks for a great project.

**Is your feature request related to a problem? Please describe.**
I am currently experiencing BLE beacons rapidly switching between rooms so I would like to tune my setup. If current RSSI and advertised measured power were available /entities API in would give more data for me to use whilst tuning. 

**Describe the solution you'd like**
Display RSSI and adverteiised measured power in /entities API 

**Describe alternatives you've considered**
I could check the logs

**Additional context**
I need to tune my room presence detection and without these values it's difficult.

**Comment by mKeRix** [comment] 2020-05-30 07:39
This is sort of a duplicate of #140 - but I'll keep this open as well since your request also includes the measured power. I agree that this would make tuning much easier, so I would like to tackle this task rather sooner than later.

**Comment by mKeRix** [comment] 2020-05-31 17:57
This has been added in 2.8.0! :tada:

**Closed by mKeRix** 2020-05-31 17:57 UTC
Labels: enhancement

**Comment by marrold** [comment] 2020-05-31 18:07
Awesome, thanks!
